title: JOHN RICHARD SCHUMACHER # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 I am a Cognitive Psychology Doctoral Candidate at Texas Tech University.  I have expertise in experimental research and inferential statistical modeling.
  <br><br>
  <a href="/pdf/Schumacher_Resume_BS.pdf">General Resume</a>
  <br>
  <a href="/pdf/Schumacher_Resume__UX.pdf">UX Focused Resume</a>
  <br>
   <a href="/pdf/Schumacher_CV.pdf">CV</a>
  <br>
  <a href="/pdf/UXWork.pdf">UX Work Sample</a>
  <br>
  <a href="https://www.linkedin.com/in/john-schumacher-15a608196/">LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-155354722-1 # your Google Analytics tracking ID here
